almacenieez/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('usuario/', include('usuario.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('departamentos/', include('departamentos.urls')),
]

proveedores/urls.py
from django.urls import path
from . import views

app_name = 'proveedores'

urlpatterns = [
    path('lista/', views.ProveedorList.as_view(), name='lista'),
    path('nuevo/', views.ProveedorCrear.as_view(), name='nuevo'),    
]

usuario/urls.py
from django.urls import path
from . import views

app_name = 'usuario'

urlpatterns = [    
    path('nuevo/', views.NuevoUsuario.as_view(), name='nuevo'),
    path('lista/', views.UsuarioList.as_view(), name='lista'),
    path('login/', views.LoginUsuario.as_view(), name='login'),
    path('signup/', views.SignupUsuario.as_view(), name='signup'),
     path('eliminar/<int:pk>', views.UsuarioDelete.as_view(), name='eliminar'),
    path('editar/<int:pk>', views.UsuarioActualizar.as_view(), name='editar'),
    path('logout/', views.logout_view, name='logout'),
    
]

proveedores/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class Proveedor(models.Model):
    nombre = models.CharField("Nombre", max_length=40, unique=False)
    direccion = models.CharField("Dirección", max_length=40, unique=False)
    telefono = models.IntegerField("Teléfono")
    #nombre = models.ForeignKey("materiales.TipoMaterial", verbose_name="Nombre", on_delete=models.CASCADE) 

    def __str__ (self):
        return self.nombre

    

proveedores/forms.py
from django import forms
from .models import Proveedor

class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = '__all__'
        widgets = {
            # 'nombre':forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Nombre del Material', 'onFOcus':'validar{this}'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'direccion': forms.Textarea(attrs={'rows':2, 'cols':20,'class': 'form-control'}),
            'telefono': forms.NumberInput(attrs={'class': 'form-control'}),

        }

proveedores/views.py
from django.shortcuts import render, redirect
from .models import Proveedor
from .forms import ProveedorForm
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.urls import reverse_lazy

# Create your views here.
class ProveedorList(ListView):
    #permission_required = 'auth.administrador_permiso'
    paginate_by = 10
    model = Proveedor
    context_object_name = 'proveedores'
    extra_context = {'etiqueta': 'Lista', 'mt_lista': True}

class ProveedorCrear( CreateView):
    model = Proveedor
    form_class = ProveedorForm
    extra_context = {'etiqueta': 'Nuevo', 'boton': 'Agregar', 'mt_nuevo': True}
    success_url = reverse_lazy('proveedores:lista')

proveedores/templates/proveedores/proveedor_form.html
{% extends 'base1.html' %}

{% block titulo %}
    {{etiqueta}} Proveedor
{% endblock titulo %}


{% block contenido %}

    <h1 class="app-page-title">{{etiqueta}} Proveedor</h1>
    <hr>
    <form method="post">
        {% csrf_token %}
        
        {{ form.as_p }}
        <button type="submit" class="btn btn-info">{{boton}}</button>
    </form>


{% endblock contenido %}

proveedores/templates/proveedores/proveedor_list.html
{% extends 'base1.html' %}


{% block titulo %}
    Lista de proveedores
{% endblock titulo %}


{% block contenido %}


<h1>Lista de productos registrados</h1>

<hr>
<a href="{% url 'proveedores:nuevo' %}" class="btn btn-primary">Nuevo Proveedor</a>
<br>
<br>
<table class="table">
    <thead class="table-dark">
        <th>Nombre</th>
        <th>Dirección</th>
        <th>Teléfono</th>
        
    </thead>
    <tbody>
        {% for proveedor in proveedores  %}
        <tr>
            <td>{{proveedor.nombre}}</td>
            <td>{{proveedor.direccion}}</td>
            <td>{{proveedor.telefono}}</td>
            <td></td>
            <td></td>

            
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock contenido %}