almacenieez/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('usuario/', include('usuario.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('departamentos/', include('departamentos.urls')),
]

usuario/urls.py
from django.urls import path
from . import views

app_name = 'usuario'

urlpatterns = [    
    path('nuevo/', views.NuevoUsuario.as_view(), name='nuevo'),
    path('lista/', views.UsuarioList.as_view(), name='lista'),
    path('login/', views.LoginUsuario.as_view(), name='login'),
    path('signup/', views.SignupUsuario.as_view(), name='signup'),
     path('eliminar/<int:pk>', views.UsuarioDelete.as_view(), name='eliminar'),
    path('editar/<int:pk>', views.UsuarioActualizar.as_view(), name='editar'),
    path('logout/', views.logout_view, name='logout'),
    
]

usuario/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Usuario(User):
    rfc = models.CharField(
        'RFC',
        max_length=20,
        null=True,
        blank=True,
        unique=True)

usuario/forms.py
from django import forms
from .models import Usuario



class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = '__all__'
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class':'forms-control'}),
            'rfc': forms.TextInput(attrs={'class': 'form-control'}),
            
        }

    def save(self, commit=True):
        user = super(UsuarioForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user
    
class UsuarioFormLog(forms.ModelForm):
    class Meta:
        model = Usuario

        fields = ('__all__')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class':'forms-control'}),
            'rfc': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def save(self, commit=True):
        user = super(UsuarioFormLog, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

usuario/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from .models import Usuario
from .forms import UsuarioForm
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UsuarioForm, UsuarioFormLog
from django.views import generic
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin
from django.views.generic import ListView, DetailView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required, permission_required



class NuevoUsuario(CreateView):
    model = Usuario
    form_class = UsuarioForm
    extra_context = {'etiqueta':'Nuevo', 'boton':'Agregar', 'nuevo_user':True}
    success_url = reverse_lazy('usuario:lista')

    def form_valid(self, form):
        user = form.save(commit=False)
        # user.is_active = 0
        # print (user)
        return super().form_valid(form)
    
class UsuarioList( ListView):
    paginate_by = 10
    model = Usuario
    context_object_name = 'usuario'
    lista_grupos = Group.objects.all()
    extra_context={'us_lista':True}

def logout_view(request):
    logout(request)
    return redirect('usuario:login')

class LoginUsuario(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm

class SignupUsuario(CreateView):
    template_name = 'signup.html'
    model = Usuario
    form_class = UsuarioFormLog
    #extra_context = {'etiqueta':'Nuevo', 'boton':'Agregar', 'nuevo_user':True}
    success_url = reverse_lazy('usuario:login')





# Create your views here.
class NuevoUsuario(CreateView):
    model = Usuario
    form_class = ('first_name','username','password','rfc')
    extra_context = {'etiqueta': 'Nuevo', 'boton': 'Agregar'}
    success_url = reverse_lazy('usuario:lista')

    def form_valid(self, form):
        user = form.save(commit=False)
        return super().form_valid(form)

    
class UsuarioActualizar( UpdateView):
    model = Usuario
    fields = ('first_name','username','password','rfc')
    extra_context = {'etiqueta': 'Actualizar', 'boton': 'Guardar'}
    success_url = reverse_lazy('usuario:lista')



class UsuarioDelete( DeleteView):
    model = Usuario
    extra_context = {'etiqueta':'Eliminar', 'user_del':True}
    success_url = reverse_lazy('usuario:lista')


def eliminar_usuario(id):
    Usuario = get_object_or_404(Usuario, id=id)
    Usuario.delete()

    return redirect('usuario:lista')


class UsuarioDetalle( DetailView):
    model = Usuario
    extra_context = {'etiqueta':'Detalles', 'boton':'Regresar'}


def editar(request, id):
    usuario = Usuario.objects.get(id=id)
    form = UsuarioForm(instance=usuario)
    if request.method == 'POST':
        form = UsuarioForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect('usuarios:lista')
    context = {'form': form }
    return render(request, 'editar_usuario.html', context) 

usuario/templates/usuario/usuario_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Usuario</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p>Quieres eliminar el usuario "{{ object }}"?</p>
        <input type="submit" value="Sí, si quiero">
        <a href="{% url 'usuario:lista' %}">Mejor no</a>
    </form>
</body>
</html>

usuario/templates/usuario/usuario_form.html
{% extends 'base1.html' %}
{% load static %}

{% block titulo %}
    Actualizacion de Usuarios
{% endblock titulo %}
    

{% block contenido %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Actualizar usuario</title>
</head>
<body>
    <h1>Actualizar usuario</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-info" >Guardar</button>
    </form>
</body>
</html>

{% endblock contenido %}


{% block js %}
    <script src="{% static 'js/funciones.js' %}" ></script>    
{% endblock js %}

usuario/templates/usuario/usuario_list.html
{% extends 'base1.html' %}

{% block titulo %}
    Lista de Usuarios
{% endblock titulo %}

{% block contenido %}
<h1 class="app-page-title">Lista de Usuarios</h1>
<hr>
<a href="{% url 'usuario:nuevo' %}" style="background-color:#0a0a0a" class="btn btn-primary">Nuevo Usuario</a>
<br>
<br>
<div class="app-card app-card-orders-lable shadow-sm mb-s">
  
  
 
  <table class="table  table-borderless">
      <thead class="table-dark">
          <th>Nombre de Usuario</th>
          
          
          
          <th>Acciones</th>
      </thead>
      <tbody>
          {% for usr in usuario %}
          <tr>
                <td>{{usr.username}}</td>
                
                <td>
                    
                        <div lass="btn-group" role="group" aria-label="Basic outlined example">
                        <a  href="{% url 'usuario:editar' usr.id %}"  style="background-color:#0a0a0a" class="btn btn-primary" >Editar</a>
                      
                        <a href="{% url 'usuario:eliminar' usr.id %}" style="background-color:#0a0a0a" class="btn btn-primary">Eliminar</a>
                    </div>
                </td>
          </tr>
          {% endfor %}
      </tbody>
  </table>
</div>



 
  
{% endblock contenido %}