almacenieez/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('usuario/', include('usuario.urls')),
    path('proveedores/', include('proveedores.urls')),
    path('departamentos/', include('departamentos.urls')),
]

departamentos/urls.py
from django.urls import path
from . import views

app_name = 'departamentos'

urlpatterns = [
    path('lista/', views.DepartamentoList.as_view(), name='lista'),
    path('nuevo/', views.DepartamentoCrear.as_view(), name='nuevo'),
    path('eliminar/<int:pk>', views.DepartamentoDelete.as_view(), name='eliminar'),
    


]

usuario/urls.py
from django.urls import path
from . import views

app_name = 'usuario'

urlpatterns = [    
    path('nuevo/', views.NuevoUsuario.as_view(), name='nuevo'),
    path('lista/', views.UsuarioList.as_view(), name='lista'),
    path('login/', views.LoginUsuario.as_view(), name='login'),
    path('signup/', views.SignupUsuario.as_view(), name='signup'),
     path('eliminar/<int:pk>', views.UsuarioDelete.as_view(), name='eliminar'),
    path('editar/<int:pk>', views.UsuarioActualizar.as_view(), name='editar'),
    path('logout/', views.logout_view, name='logout'),
    
]

departamentos/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Departamentos(models.Model):
    nombre = models.CharField(
        'nombre',
        max_length=100,
        null=True,
        blank=True,
        unique=True)

departamentos/forms.py
from django import forms
from .models import Departamentos

class DepartamentoForm(forms.ModelForm):
    class Meta:
        model = Departamentos
        fields = '__all__'
        widgets = {
            # 'nombre':forms.TextInput(attrs = {'class':'form-control', 'placeholder':'Nombre del Material', 'onFOcus':'validar{this}'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),

        }

departamentos/views.py
from django.shortcuts import render, redirect
from .models import Departamentos
from .forms import DepartamentoForm
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.urls import reverse_lazy

# Create your views here.

class DepartamentoList(ListView):
    #permission_required = 'auth.administrador_permiso'
    paginate_by = 10
    model = Departamentos
    context_object_name = 'departamentos'
    extra_context = {'etiqueta': 'Lista', 'mt_lista': True}

class DepartamentoCrear( CreateView):
    model = Departamentos
    form_class = DepartamentoForm
    extra_context = {'etiqueta': 'Nuevo', 'boton': 'Agregar', 'dpto_nuevo': True}
    success_url = reverse_lazy('departamentos:lista')


class DepartamentoDelete( DeleteView):
    model = Departamentos
    extra_context = {'etiqueta':'Eliminar', 'user_del':True}
    success_url = reverse_lazy('departamentos:lista')

def eliminar_departamento(id):
    Departamentos = get_object_or_404(Departamentos, id=id)
    Departamentos.delete()

    return redirect('departamentos:lista')

departamentos/templates/departamentos/departamentos_confirm_delete.html
{% extends 'base1.html' %}
{% block contenido %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Departamento</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p>Quieres eliminar el departamento "{{ object }}"?</p>
        <input type="submit" value="Sí, si quiero">
        <a href="{% url 'departamentos:lista' %}">Mejor no</a>
    </form>
</body>
</html>
{% endblock contenido %}

departamentos/templates/departamentos/departamentos_form.html
{% extends 'base1.html' %}

{% block titulo %}
    {{etiqueta}} Departamento
{% endblock titulo %}


{% block contenido %}

    <h1 class="app-page-title">{{etiqueta}} Departamento</h1>
    <hr>
    <form method="post">
        {% csrf_token %}
        
        {{ form.as_p }}
        <button type="submit" class="btn btn-info">{{boton}}</button>
    </form>


{% endblock contenido %}

departamentos/templates/departamentos/departamentos_list.html
{% extends 'base1.html' %}


{% block titulo %}
    Lista de productos
{% endblock titulo %}


{% block contenido %}


<h1 class="app-page-title">Lista de Departamentos</h1>
<div class="app-card app-card-orders-lable shadow-sm mb-s" id="tabla-departamentos"></div>

<hr>
<a href="{% url 'departamentos:nuevo' %}" style="background-color:#0a0a0a" class="btn btn-primary">Nuevo Departamento</a>

<br>
<br>
<table class="table  table-borderless">
    <thead class="table-dark">
        <th>Nombre</th>


        <th>Acciones</th>
    

    <tbody>
        {% for depto in departamentos  %}
        <tr>
            <td>{{depto.nombre}}</td>
            
            <td>   
                <div lass="btn-group" role="group" aria-label="Basic outlined example">
                    <a  method="POST" href="{% url 'departamentos:eliminar' depto.id %}" style="background-color:#0a0a0a" class="btn btn-primary">Eliminar</a>
                </div>
           </td>
        </tr>
        {% endfor %}
    </thead>
    </tbody>
</table>

{% endblock contenido %}